// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrFwQv1gEgIVTokaGj6EudFnJmSfpiDAY',
    appId: '1:513914181670:web:8e328494094e948bb2aee7',
    messagingSenderId: '513914181670',
    projectId: 'mounarchtech-ac3b9',
    authDomain: 'mounarchtech-ac3b9.firebaseapp.com',
    storageBucket: 'mounarchtech-ac3b9.firebasestorage.app',
    measurementId: 'G-3BZPVX1DLN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzppyk8HYetSsbvPhFfJG793njHiAtwNc',
    appId: '1:513914181670:android:8e258c3619d7546ab2aee7',
    messagingSenderId: '513914181670',
    projectId: 'mounarchtech-ac3b9',
    storageBucket: 'mounarchtech-ac3b9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkdsbqI-2seUJRQOOZFSz4jt-G_6n8iRA',
    appId: '1:513914181670:ios:0483c14353c5e06bb2aee7',
    messagingSenderId: '513914181670',
    projectId: 'mounarchtech-ac3b9',
    storageBucket: 'mounarchtech-ac3b9.firebasestorage.app',
    iosBundleId: 'com.example.mounarch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkdsbqI-2seUJRQOOZFSz4jt-G_6n8iRA',
    appId: '1:513914181670:ios:0483c14353c5e06bb2aee7',
    messagingSenderId: '513914181670',
    projectId: 'mounarchtech-ac3b9',
    storageBucket: 'mounarchtech-ac3b9.firebasestorage.app',
    iosBundleId: 'com.example.mounarch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrFwQv1gEgIVTokaGj6EudFnJmSfpiDAY',
    appId: '1:513914181670:web:697cbfa018358481b2aee7',
    messagingSenderId: '513914181670',
    projectId: 'mounarchtech-ac3b9',
    authDomain: 'mounarchtech-ac3b9.firebaseapp.com',
    storageBucket: 'mounarchtech-ac3b9.firebasestorage.app',
    measurementId: 'G-2PW1QQ60GS',
  );
}
